### ISSUE TITLE
iOS分享小程序错误

### ISSUE THREAD

**Issue by fantasyStyle** [An-uking/flutter_umengshare#2]
在UmengsharePlugin.m 中对传入方法的判断出现两处login 另一个就是在调用小程序分享时传入的currentViewController 应该为nil .在附件中已经做好了标注 
<img width="614" alt="屏幕快照 2019-04-03 下午12 02 02" src="https://user-images.githubusercontent.com/16890525/55452259-69b9f600-5609-11e9-99e1-027edabd6b87.png">
<img width="1078" alt="屏幕快照 2019-04-03 下午12 04 02" src="https://user-images.githubusercontent.com/16890525/55452263-6aeb2300-5609-11e9-8695-50d51855c2fb.png">

**Comment by An-uking** [comment]
嗯 好的 谢谢 最近忙其他项目 这个库抽时间更新一下
